# Add 'repo' label to any root file changes
repo:
  - ./*

frontend:
  - src/*
  - src/**/*

backend-root:
  - buying_selling/*
  - buying_selling/**/*

backend:
  - posts/*
  - posts/**/*
  - users/*
  - users/**/*
